//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class artEntities : DbContext
    {
        public artEntities()
            : base("name=artEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActFlow> ActFlows { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<Artifact> Artifacts { get; set; }
        public DbSet<ArtifactType> ArtifactTypes { get; set; }
        public DbSet<ArtifactTypeBonu> ArtifactTypeBonus { get; set; }
        public DbSet<Bonu> Bonus { get; set; }
        public DbSet<Constellation> Constellations { get; set; }
        public DbSet<ConstellationBonu> ConstellationBonus { get; set; }
        public DbSet<Statistic> Statistics { get; set; }
        public DbSet<Step> Steps { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Talent> Talents { get; set; }
        public DbSet<UserArtifact> UserArtifacts { get; set; }
        public DbSet<UserTalent> UserTalents { get; set; }
    }
}
